### ISSUE TITLE
Error importing NREL_CSM.config at example.py file

### ISSUE THREAD

**Issue by SamAct** [WISDEM/NREL_CSM#2]
> 
  File "C:/WRA_files/Files/NREL_CSM-master/NREL_CSM-master/docs/examples/example.py", line 3, in <module>
    from NREL_CSM.config import *

ImportError: No module named NREL_CSM.config

This is the error that I got. I couldn't find any file named NREL_CSM.config in the folder. Please review. Are you trying to point  towards the whole NREL_CSM model at line 3?

Thanks

**Comment by dykesk** [comment]
the file is config.py and it is in the src/nrel_csm folder.  When you install the model, python will see things address based on the directory structure in src - hence, nrel_csm.config.  Python is case sensitive so it thinks NREL_CSM.config and nrel_csm.config are different so you would need to change the file line 3 in example.py to from nrel_csm.config import * 

Note - this code is not currently supported but if you want to do a pull request for this issue (and any others that you find) then I'll happily merge it to master.
