### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by mckatie1** [WISDEM/NREL_CSM#5]
File "C:/Wisdem/WISDEM/wisdem/nrelcsm/nrel_csm_run.py", line 11, in <module>
    from wisdem.nrelcsm.nrel_csm import bos_csm

ModuleNotFoundError: No module named 'wisdem'

I am receiving the above error.  I am not sure if maybe it is because I haven't properly installed the Wisdem library, but I can't seem to figure out how to install it since it's not a default library.

Would love any help I can get.  Thanks

**Comment by gbarter** [comment]
Sorry I didn't see this until now.  It looks like you have not installed WISDEM properly.  Try 'conda install wisdem'.  You can also access the NREL CSM through [SAM](https://sam.nrel.gov/).
